package proof

import (
	"bytes"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/json"
	"encoding/pem"
	"math/big"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"testing"
	"time"

	"github.com/zeylos/excalidraw-wopi/internal/config"
)

// TestGoldenVectors reproduces internal/proof/testdata/vectors.json,
// generated by tools/proofvectors/generate.py against Drive's own
// verify_wopi_proof. A pass here means this package's byte layout, its
// uppercasing rule, and its PKCS1v15/SHA-256 signing match what Drive
// verifies, not only a Go-side reimplementation of the same rules.
func TestGoldenVectors(t *testing.T) {
	ks := loadTestKeySet(t)

	type vector struct {
		Description     string `json:"description"`
		Token           string `json:"token"`
		URL             string `json:"url"`
		Ticks           int64  `json:"ticks"`
		Signature       string `json:"signature"`
		VerifiedByDrive bool   `json:"verified_by_drive"`
	}

	data, err := os.ReadFile(filepath.Join("testdata", "vectors.json"))
	if err != nil {
		t.Fatalf("read vectors.json: %v", err)
	}
	var vectors []vector
	if err := json.Unmarshal(data, &vectors); err != nil {
		t.Fatalf("unmarshal vectors.json: %v", err)
	}
	if len(vectors) == 0 {
		t.Fatal("vectors.json holds no vectors")
	}

	for _, v := range vectors {
		t.Run(v.Description, func(t *testing.T) {
			if !v.VerifiedByDrive {
				t.Fatalf("vector %q was not marked verified_by_drive by the generator", v.Description)
			}

			gotProof, gotProofOld, gotTimestamp := ks.SignRequest(v.Token, v.URL, ticksToTime(v.Ticks))

			if gotProof != v.Signature {
				t.Errorf("X-WOPI-Proof mismatch\n got:  %s\n want: %s", gotProof, v.Signature)
			}
			// The test key set has old == current (see testdata/test_key.pem),
			// so the old-key signature must equal the same golden value.
			if gotProofOld != v.Signature {
				t.Errorf("X-WOPI-ProofOld mismatch\n got:  %s\n want: %s", gotProofOld, v.Signature)
			}
			wantTimestamp := strconv.FormatInt(v.Ticks, 10)
			if gotTimestamp != wantTimestamp {
				t.Errorf("X-WOPI-Timestamp = %s, want %s", gotTimestamp, wantTimestamp)
			}
		})
	}
}

func loadTestKeySet(t *testing.T) *KeySet {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", "test_key.pem"))
	if err != nil {
		t.Fatalf("read test_key.pem: %v", err)
	}
	ks, err := parseKeySet(data)
	if err != nil {
		t.Fatalf("parse test_key.pem: %v", err)
	}
	return ks
}

func TestSignedBaseLayout(t *testing.T) {
	got := signedBase("tok", "https://example.org/x", 0)

	var want []byte
	want = append(want, 0, 0, 0, 3) // len("tok")
	want = append(want, "tok"...)
	upperURL := "HTTPS://EXAMPLE.ORG/X"
	want = append(want, 0, 0, 0, byte(len(upperURL))) // len fits one byte here
	want = append(want, upperURL...)
	want = append(want, 0, 0, 0, 8) // ticks length prefix, always 8
	want = append(want, 0, 0, 0, 0, 0, 0, 0, 0)

	if !bytes.Equal(got, want) {
		t.Errorf("signedBase =\n%x\nwant\n%x", got, want)
	}
}

func TestSignedBaseUppercasesURLOnly(t *testing.T) {
	got := signedBase("MixedCaseToken", "https://Example.ORG/Path?Query=Value", 0)

	if !bytes.Contains(got, []byte("MixedCaseToken")) {
		t.Error("the token must stay untouched by uppercasing")
	}
	if bytes.Contains(got, []byte("Example.ORG/Path")) {
		t.Error("the URL must be uppercased before it is encoded")
	}
	if !bytes.Contains(got, []byte("HTTPS://EXAMPLE.ORG/PATH?QUERY=VALUE")) {
		t.Error("the uppercased URL must appear in the signed base")
	}
}

// ticksToTime converts .NET DateTime ticks back to a time. It exists for
// this package's tests only: production code only ever converts a time to
// ticks (TimeToTicks), never back.
func ticksToTime(ticks int64) time.Time {
	return time.Unix(0, (ticks-dotnetEpochTicks)*100).UTC()
}

func TestTicksRoundTripsUnixEpoch(t *testing.T) {
	epoch := time.Unix(0, 0).UTC()

	gotTicks := TimeToTicks(epoch)
	if gotTicks != dotnetEpochTicks {
		t.Errorf("TimeToTicks(unix epoch) = %d, want %d", gotTicks, dotnetEpochTicks)
	}

	gotTime := ticksToTime(dotnetEpochTicks)
	if !gotTime.Equal(epoch) {
		t.Errorf("ticksToTime(dotnetEpochTicks) = %v, want %v", gotTime, epoch)
	}
}

func TestTicksRoundTripsArbitraryTimes(t *testing.T) {
	cases := []time.Time{
		time.Date(2026, 8, 21, 12, 30, 0, 0, time.UTC),
		time.Date(1901, 1, 1, 0, 0, 0, 0, time.UTC),
		time.Date(2100, 1, 1, 0, 0, 0, 0, time.UTC),
		time.Date(2026, 8, 21, 12, 30, 0, 123400000, time.UTC), // sub-second precision to 100 ns
	}

	for _, want := range cases {
		ticks := TimeToTicks(want)
		got := ticksToTime(ticks)
		if !got.Equal(want) {
			t.Errorf("round trip for %v: got %v (ticks=%d)", want, got, ticks)
		}
	}
}

// TestFirstStartGeneratesAndPersists checks the ONLYOFFICE-precedent
// lifecycle: an absent key file gets a fresh RSA key, with the old slot
// equal to the current key, persisted for next boot.
func TestFirstStartGeneratesAndPersists(t *testing.T) {
	dir := t.TempDir()
	keyPath := filepath.Join(dir, "proof-key.pem")
	cfg := config.Config{ProofKeyPath: keyPath}

	if _, err := os.Stat(keyPath); !os.IsNotExist(err) {
		t.Fatalf("test setup: key file must not exist yet, stat err = %v", err)
	}

	ks, err := Load(cfg)
	if err != nil {
		t.Fatalf("Load() on first start: %v", err)
	}
	if ks.Current == nil {
		t.Fatal("Load() did not generate a current key")
	}
	if !ks.Old.Equal(ks.Current) {
		t.Error("on first start, the old key must equal the current key")
	}

	data, err := os.ReadFile(keyPath)
	if err != nil {
		t.Fatalf("Load() did not persist the key file: %v", err)
	}
	if len(data) == 0 {
		t.Fatal("persisted key file is empty")
	}

	reloaded, err := Load(cfg)
	if err != nil {
		t.Fatalf("Load() on reload: %v", err)
	}
	if !reloaded.Current.Equal(ks.Current) {
		t.Error("reload must return the same current key as the persisted file")
	}
	if !reloaded.Old.Equal(ks.Old) {
		t.Error("reload must return the same old key as the persisted file")
	}
}

// TestEnvInjectionWinsOverPath checks that EXCALIDRAW_WOPI_PROOF_KEY_PEM
// content, when set, is used instead of cfg.ProofKeyPath, and that Load
// does not touch the filesystem path in that case (the Kubernetes-secret
// injection path).
func TestEnvInjectionWinsOverPath(t *testing.T) {
	dir := t.TempDir()
	keyPath := filepath.Join(dir, "unused-proof-key.pem")
	cfg := config.Config{ProofKeyPath: keyPath}

	envKS := generateTestKeySet(t)
	pemContent, err := encodeKeySet(envKS)
	if err != nil {
		t.Fatalf("encode env key set: %v", err)
	}
	t.Setenv(EnvPEMVar, string(pemContent))

	ks, err := Load(cfg)
	if err != nil {
		t.Fatalf("Load() with env PEM set: %v", err)
	}
	if !ks.Current.Equal(envKS.Current) {
		t.Error("Load() must use the key from the env var, not generate a new one")
	}
	if !ks.Old.Equal(envKS.Old) {
		t.Error("Load() must use the old key from the env var")
	}

	if _, err := os.Stat(keyPath); !os.IsNotExist(err) {
		t.Errorf("Load() must not create %s when the env var is set, stat err = %v", keyPath, err)
	}
}

func generateTestKeySet(t *testing.T) *KeySet {
	t.Helper()
	cfg := config.Config{ProofKeyPath: filepath.Join(t.TempDir(), "proof-key.pem")}
	ks, err := Load(cfg)
	if err != nil {
		t.Fatalf("generate a throwaway key set: %v", err)
	}
	return ks
}

func TestPublicKeyPartsAreBase64(t *testing.T) {
	ks := loadTestKeySet(t)

	parts, err := ks.CurrentPublicParts()
	if err != nil {
		t.Fatalf("CurrentPublicParts(): %v", err)
	}
	if parts.Value == "" || parts.Modulus == "" || parts.Exponent == "" {
		t.Fatalf("CurrentPublicParts() returned an empty field: %+v", parts)
	}
	// AQAB is base64 for the common public exponent 65537, used by every
	// key this package generates (rsa.GenerateKey's default exponent).
	if parts.Exponent != "AQAB" {
		t.Errorf("Exponent = %q, want %q", parts.Exponent, "AQAB")
	}

	oldParts, err := ks.OldPublicParts()
	if err != nil {
		t.Fatalf("OldPublicParts(): %v", err)
	}
	if oldParts.Modulus != parts.Modulus {
		t.Error("the test key set has old == current, so their modulus must match")
	}
}

// TestParseKeySetRejectsEmptyInput checks that an empty source must fail
// loudly instead of yielding a KeySet with nil keys that panics on first
// use.
func TestParseKeySetRejectsEmptyInput(t *testing.T) {
	if _, err := parseKeySet(nil); err == nil {
		t.Error("parseKeySet(nil) must return an error, not a KeySet with nil keys")
	}
	if _, err := parseKeySet([]byte("")); err == nil {
		t.Error("parseKeySet(\"\") must return an error")
	}
}

func TestParseKeySetRejectsGarbagePEM(t *testing.T) {
	if _, err := parseKeySet([]byte("this is not PEM content at all")); err == nil {
		t.Error("parseKeySet() on garbage input must return an error")
	}
}

func TestParseKeySetRejectsTruncatedPEM(t *testing.T) {
	full, err := encodeKeySet(generateTestKeySet(t))
	if err != nil {
		t.Fatalf("encodeKeySet(): %v", err)
	}
	// Cut before any "-----END" marker, so no block in the file is
	// complete; a cut past the first block's end would leave a valid
	// current key and only drop the old key, which parseKeySet tolerates
	// on purpose (old falls back to current).
	truncated, _, found := bytes.Cut(full, []byte("-----END"))
	if !found {
		t.Fatal("test setup: encoded key set has no END marker")
	}

	if _, err := parseKeySet(truncated); err == nil {
		t.Error("parseKeySet() on truncated PEM must return an error")
	}
}

// TestParseKeySetRejectsSmallKey checks that an injected key under the
// minimum modulus size must be rejected before it ever
// reaches mustSign, which panics instead of returning an error. It builds
// the 512-bit key by hand: rsa.GenerateKey itself refuses to generate
// anything under 1024 bits.
func TestParseKeySetRejectsSmallKey(t *testing.T) {
	small := generateInsecureRSAKey(t, 512)
	der, err := x509.MarshalPKCS8PrivateKey(small)
	if err != nil {
		t.Fatalf("marshal 512-bit key: %v", err)
	}
	pemBytes := pem.EncodeToMemory(&pem.Block{Type: pemBlockType, Bytes: der})

	if _, err := parseKeySet(pemBytes); err == nil {
		t.Error("parseKeySet() on a 512-bit key must return an error, not accept it")
	}
}

// generateInsecureRSAKey builds a mathematically valid RSA key below the
// size rsa.GenerateKey allows, for testing the minRSAKeyBits rejection.
func generateInsecureRSAKey(t *testing.T, bits int) *rsa.PrivateKey {
	t.Helper()
	primeBits := bits / 2
	p, err := rand.Prime(rand.Reader, primeBits)
	if err != nil {
		t.Fatalf("generate prime p: %v", err)
	}
	q, err := rand.Prime(rand.Reader, primeBits)
	if err != nil {
		t.Fatalf("generate prime q: %v", err)
	}

	one := big.NewInt(1)
	phi := new(big.Int).Mul(new(big.Int).Sub(p, one), new(big.Int).Sub(q, one))
	e := big.NewInt(65537)
	d := new(big.Int).ModInverse(e, phi)
	if d == nil {
		t.Fatal("test setup: e has no inverse mod phi(n), pick different primes")
	}

	key := &rsa.PrivateKey{
		PublicKey: rsa.PublicKey{N: new(big.Int).Mul(p, q), E: int(e.Int64())},
		D:         d,
		Primes:    []*big.Int{p, q},
	}
	key.Precompute()
	return key
}

// TestPersistRaceReReadsWinnersFile checks that when persist loses the
// create race (the destination file already exists), it must
// discard its own generated key and adopt the key already on disk,
// instead of silently overwriting a sibling replica's persisted key.
func TestPersistRaceReReadsWinnersFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "proof-key.pem")

	winner := generateTestKeySet(t)
	winnerPEM, err := encodeKeySet(winner)
	if err != nil {
		t.Fatalf("encode winner key set: %v", err)
	}
	if err := os.WriteFile(path, winnerPEM, 0o600); err != nil {
		t.Fatalf("simulate an existing (winning) file: %v", err)
	}

	loser := generateTestKeySet(t)
	got, err := persist(path, loser)
	if err != nil {
		t.Fatalf("persist() on a losing race: %v", err)
	}
	if !got.Current.Equal(winner.Current) {
		t.Error("persist() must return the winner's key when it loses the create race")
	}
	if got.Current.Equal(loser.Current) {
		t.Error("persist() must not return the loser's own generated key")
	}

	onDisk, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	replayed, err := parseKeySet(onDisk)
	if err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	if !replayed.Current.Equal(winner.Current) {
		t.Error("the loser must not have clobbered the winner's file on disk")
	}
}

// TestSignedURLsAreASCII documents and pins down why signedBase's
// strings.ToUpper call needs no extra ASCII guard: every WOPISrc this
// service signs comes from an allowlisted origin with a UUID path, so it
// is pure ASCII after url.Parse, and Go's simple case mapping never
// diverges from Python's str.upper() on ASCII input.
func TestSignedURLsAreASCII(t *testing.T) {
	urls := []string{
		"http://localhost:8000/api/v1.0/wopi/files/3fa85f64-5717-4562-b3fc-2c963f66afa6",
		"https://drive.example.org/api/v1.0/wopi/files/00000000-0000-0000-0000-000000000000/contents",
		"https://drive.example.org:8443/api/v1.0/wopi/files/abc123?access_token=tok",
	}
	for _, raw := range urls {
		u, err := url.Parse(raw)
		if err != nil {
			t.Fatalf("url.Parse(%q): %v", raw, err)
		}
		s := u.String()
		for i := 0; i < len(s); i++ {
			if s[i] > 127 {
				t.Errorf("%q contains a non-ASCII byte", s)
				break
			}
		}
	}
}
