#!/usr/bin/env python3
"""Generate golden vectors for WOPI proof signing.

Each vector runs through Drive's own `build_expected_proof` to build the
signed base, signs it with a fixed test RSA key, and then runs the
signature back through Drive's own `verify_wopi_proof` to confirm Drive
accepts it. The Go test suite in internal/proof reproduces the signature
byte-for-byte and checks it against the stored value.

Usage:
    generate.py /path/to/a/clone/of/suitenumerique/drive

Output:
    internal/proof/testdata/vectors.json
    internal/proof/testdata/test_key.pem (created once, then reused)
"""

import base64
import importlib.util
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa

DOTNET_EPOCH_TICKS = 621355968000000000
TICKS_PER_SECOND = 10000000

HERE = Path(__file__).resolve().parent
TESTDATA = HERE.parent.parent / "internal" / "proof" / "testdata"
KEY_PATH = TESTDATA / "test_key.pem"
VECTORS_PATH = TESTDATA / "vectors.json"

KEY_FILE_HEADER = (
    "# TEST-ONLY RSA private key for internal/proof golden vectors.\n"
    "# Generated by tools/proofvectors/generate.py. Never use it outside tests.\n"
)


def load_drive_signature_module(drive_root: Path):
    """Import Drive's signature.py by file path, so no Django settings are needed."""
    path = drive_root / "src" / "backend" / "wopi" / "utils" / "signature.py"
    if not path.is_file():
        raise SystemExit(f"cannot find signature.py under {drive_root}: {path}")
    spec = importlib.util.spec_from_file_location("drive_wopi_signature", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def load_or_create_test_key() -> rsa.RSAPrivateKey:
    """Load the committed test key, or generate and commit one on first run."""
    if KEY_PATH.is_file():
        text = KEY_PATH.read_bytes()
        marker = text.index(b"-----BEGIN")
        return serialization.load_pem_private_key(text[marker:], password=None)

    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    TESTDATA.mkdir(parents=True, exist_ok=True)
    KEY_PATH.write_bytes(KEY_FILE_HEADER.encode("ascii") + pem)
    return private_key


def public_key_pem(private_key: rsa.RSAPrivateKey) -> bytes:
    return private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )


def ticks_for(dt: datetime) -> int:
    """Convert a UTC datetime to .NET DateTime ticks, the WOPI timestamp unit."""
    unix_seconds = dt.timestamp()
    return DOTNET_EPOCH_TICKS + round(unix_seconds * TICKS_PER_SECOND)


def sign(private_key: rsa.RSAPrivateKey, base: bytes) -> str:
    signature = private_key.sign(base, padding.PKCS1v15(), hashes.SHA256())
    return base64.b64encode(signature).decode("ascii")


# Each entry: (description, token, url, timestamp).
# Coverage: short and long tokens, non-ASCII token bytes, a query string,
# an already-uppercase URL, a lowercase host, and an access_token query
# parameter, since Drive keeps the token in the query on real requests.
VECTOR_DEFS = [
    (
        "short token, plain url",
        "tok",
        "https://drive.example.org/api/v1.0/wopi/files/11111111-1111-1111-1111-111111111111",
        datetime(2026, 1, 1, 0, 0, 0, tzinfo=timezone.utc),
    ),
    (
        "long token, contents url",
        "a" * 256,
        "https://drive.example.org/api/v1.0/wopi/files/22222222-2222-2222-2222-222222222222/contents",
        datetime(2026, 3, 15, 8, 30, 45, tzinfo=timezone.utc),
    ),
    (
        "non-ASCII token bytes",
        "tok-éè中文-\U0001F600",
        "https://drive.example.org/api/v1.0/wopi/files/33333333-3333-3333-3333-333333333333",
        datetime(2026, 6, 1, 12, 0, 0, 123456, tzinfo=timezone.utc),
    ),
    (
        "url with access_token query string",
        "opaque-token-value-42",
        "https://drive.example.org/api/v1.0/wopi/files/44444444-4444-4444-4444-444444444444/contents"
        "?access_token=opaque-token-value-42&access_token_ttl=36000000",
        datetime(2026, 8, 21, 9, 15, 0, tzinfo=timezone.utc),
    ),
    (
        "mixed-case url, query already uppercase",
        "TokenWithMixedCase",
        "https://Drive.Example.ORG/API/v1.0/Wopi/Files/55555555-5555-5555-5555-555555555555"
        "?Access_Token=ALREADY-UPPER",
        datetime(2025, 12, 31, 23, 59, 59, tzinfo=timezone.utc),
    ),
    (
        "single character token",
        "x",
        "https://drive.example.org/api/v1.0/wopi/files/66666666-6666-6666-6666-666666666666",
        datetime(2026, 8, 21, 0, 0, 0, tzinfo=timezone.utc),
    ),
    (
        "timestamp near the .NET epoch, far past",
        "early-token",
        "https://drive.example.org/api/v1.0/wopi/files/77777777-7777-7777-7777-777777777777",
        datetime(1900, 1, 1, 0, 0, 0, tzinfo=timezone.utc),
    ),
    (
        "timestamp far in the future",
        "future-token",
        "https://drive.example.org/api/v1.0/wopi/files/88888888-8888-8888-8888-888888888888",
        datetime(2100, 1, 1, 0, 0, 0, tzinfo=timezone.utc),
    ),
]


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(f"usage: {sys.argv[0]} /path/to/drive/clone")

    drive_root = Path(sys.argv[1]).resolve()
    drive_sig = load_drive_signature_module(drive_root)

    private_key = load_or_create_test_key()
    pub_pem = public_key_pem(private_key)
    proof_keys = {"public_key": pub_pem}

    vectors = []
    for description, token, url, dt in VECTOR_DEFS:
        ticks = ticks_for(dt)
        expected_proof = drive_sig.build_expected_proof(token, url, ticks)
        signature_b64 = sign(private_key, expected_proof)

        verified = drive_sig.verify_wopi_proof(proof_keys, signature_b64, None, expected_proof)
        if not verified:
            raise SystemExit(f"drive rejected our own signature for vector: {description!r}")

        vectors.append(
            {
                "description": description,
                "token": token,
                "url": url,
                "ticks": ticks,
                "signature": signature_b64,
                "verified_by_drive": True,
            }
        )

    VECTORS_PATH.write_text(json.dumps(vectors, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(
        f"generated {len(vectors)} vectors, "
        f"verified_by_drive=True for all, "
        f"drive version checked at {drive_root}, "
        f"key={KEY_PATH.name}, output={VECTORS_PATH}"
    )


if __name__ == "__main__":
    main()
